# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZQs5jGfu4vFnSJiKvxYUB16JkwOCGC01
"""

grades=[]
names=[]
infoDic=dict()
average=dict()
try:
  print("This program will print the student with the highest average on the screen after you enter the students' information.")

  count=int(input("\nPlease write down how many student information you will enter: "))
  for x in range(count):
    name=input("\nPlease enter the name: ").title()
    surname=input("Please enter the surname: ").title()
    midterm=float(input("Please enter the midterm grade: "))
    final=float(input("Please enter the final grade: "))
    homework=float(input("Please enter the homework grade: "))
    
    names.append(name+" "+surname)
    grades.append([midterm,final,homework])
  for x in range(count):
    infoDic[names[x]]=grades[x]
  
  for item in infoDic.items():
    ave=(item[1][0]+item[1][1]+item[1][2])/3
    average[item[0]]=ave
  
  sort=sorted(average.items(), key=lambda item:item[1],reverse=True)
  
  print("\nRanking success: ")
  for x in sort:
    print(x[0]+"   "+str(x[1]))
  
  print("\nCongratulations "+sort[0][0]+" ! You have the highest average.")
except:
  print("\n\t*** You didn't enter a number! ***")