# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C4etJOMetP4ZDnbUITbE4CL49DhBzKSa
"""

def prime_first():
    for number in range(0,500):
        if number>1:
            isPrime=True
            for i in range(2,number):
                if(number%i)==0:
                    isPrime=False
                    break
            if isPrime==True:
                print(number)
            

def prime_second():
    for number in range(500,1000):
        if number>1:
            isPrime=True
            for i in range(2,number):
                if(number%i)==0:
                    isPrime=False
                    break
            if isPrime==True:
                print(number)
            

print("Prime numbers from 0 to 500: ") 
prime_first()
print("Prime numbers from 500 to 1000: ")
prime_second()